global:
  # If set, these take highest precedence and change both envoyGateway and ratelimit's container registry and pull secrets.
  # -- Global override for image registry
  imageRegistry: ""
  # -- Global override for image pull secrets
  imagePullSecrets: []
gateway-helm:
  global:
    images:
      envoyGateway:
        # This is the full image name including the hub, repo, and tag.
        image: v1.6.0
        testing: true
      ratelimit:
        # This is the full image name including the hub, repo, and tag.
        image: "docker.io/envoyproxy/ratelimit:master"
        # Specify image pull policy if default behavior isn't desired.
        # Default behavior: latest images will be Always else IfNotPresent.
        pullPolicy: IfNotPresent
        # List of secrets in the same namespace of the component that can be used to pull images from private repositories.
        pullSecrets:
            - name: my-ratelimit-secret
